name: Run publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push event but only for the master branch
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # The type of node version that the job will run on
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Run install step 
      - run: npm ci
      # Run test step
      - run: npm test
  publish:
    needs: test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # The type of node version that the job will run on
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      # Run version bump step
      - name: Run version bump
        uses: phips28/gh-action-bump-version@v8.0.18
      # Get tag step
      - name: Get tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      # Run release step
      - name: Run release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.tag.outputs.tag }}
          prerelease: false
      # Run install step 
      - run: npm ci
      # Run clean step
      - run: npm run clean
      # Run build step
      - run: npm run build:lib
      # Run publish step
      - name: Run publish
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
